### PR TITLE
[i18n] - [l10n] > improvements - update v.1.9

### PR DESCRIPTION
**Pull request by fxbenard**
Add missing text domain + French, pot updates to reflect the change

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@fxbenard Do you think you could bring this up to date to it merges cleanly? Sorry I didn't see this before.

**Comment by fxbenard** [comment]
@pippinsplugins done

**Comment by pippinsplugins** [comment]
@fxbenard Just getting to this. The 2.0 release makes some string changes. Would you be up for submitting the update to the `release/2.0` branch along with updated text strings that were just added / changed?

**Comment by fxbenard** [comment]
No problem, I will do that

**Comment by fxbenard** [comment]
Closed via #31

**Pull request closed without merging**
