### PR TITLE
Release/2.0

### PR DESCRIPTION
**Pull request by pippinsplugins**

### CODE REVIEW

**Comment by pippinsplugins** [comment]
I'd love to get some testing on this from @easydigitaldownloads/core-devs

**Comment by pippinsplugins** [comment]
Takes care of these items: https://github.com/easydigitaldownloads/edd-manual-purchases/issues?q=is%3Aissue+milestone%3A2.0+is%3Aclosed

**Comment by mindctrl** [comment]
Decimals are getting cut off and replaced with .00. For example, an item priced at $13.31 gets saved at a price of $13.00

image

image

**Comment by pippinsplugins** [comment]
Re-opening issue.

**Comment by pippinsplugins** [comment]
Should work now.

**Comment by mindctrl** [comment]
That's fixed.

Something I'm seeing with the dropdown search. I need someone else to test this because I always see issues with the dropdown.

Add an item by searching. Then add another item and search for a different word. I see the same results as the first item row.

image

In the second row in the shot above, I searched for 'bundle'. Anyone else seeing that?

**Pull request merged**
