### PR TITLE
Issue/32

### PR DESCRIPTION
**Pull request by brashrebel**

### CODE REVIEW

**Comment by brashrebel** [comment]
I'm gonna try and fix these conflicts.

**Comment by brashrebel** [comment]
This should be fine now. Spent some time on this to resolve both #32 and #34 at once. Now there's a customer dropdown as well as the option for creating a new customer. Everything is working well in my tests.

**Comment by cklosowski** [comment]
This seems to work great.

@pippinsplugins any objection with me merging and doing some final testing/fixes before releasing?

**Comment by pippinsplugins** [comment]
@cklosowski no objections.

**Pull request merged**
